from __future__ import annotations
from typing import Protocol, Optional
from logic.payroll.public.schemas import (
    Employee, Contract, PayrollPeriod, TimeInput, PayslipResult,
)


class EmployeeRepository(Protocol):
    def upsert(self, employee: Employee) -> Employee: ...
    def get(self, employee_id: str) -> Optional[Employee]: ...


class ContractRepository(Protocol):
    def upsert(self, contract: Contract) -> Contract: ...
    def get(self, contract_id: str) -> Optional[Contract]: ...
    def get_for_employee(self, employee_id: str) -> Optional[Contract]: ...


class PeriodRepository(Protocol):
    def upsert(self, period: PayrollPeriod) -> PayrollPeriod: ...
    def get(self, period_id: str) -> Optional[PayrollPeriod]: ...


class TimeInputRepository(Protocol):
    def upsert(self, time_input: TimeInput) -> TimeInput: ...
    def get(self, period_id: str, employee_id: str) -> Optional[TimeInput]: ...


class PayslipRepository(Protocol):
    def upsert(self, payslip: PayslipResult) -> PayslipResult: ...
    def get(self, period_id: str, employee_id: str) -> Optional[PayslipResult]: ...
